// Package operations contains small, deterministic helpers used by the
// operator-facing acceptance and evidence workflows.
package operations

import (
	"bytes"
	"crypto/ed25519"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/akimisaka/aor/pkg/canonicaljson"
)

const (
	// DefaultRunbookMaxAge is the acceptance window in the SPEC.
	DefaultRunbookMaxAge = 180 * 24 * time.Hour
	maxRecordBytes       = 1 << 20
	maxEvidenceFiles     = 256
	maxFieldBytes        = 4096
	maxEvidenceURIBytes  = 2048
)

var (
	ErrInvalidEvidence = errors.New("invalid runbook exercise evidence")
	ErrEvidenceStale   = errors.New("runbook exercise evidence is stale")
	ErrEvidenceMissing = errors.New("runbook exercise evidence is incomplete")

	digestPattern = regexp.MustCompile(`^sha256:[0-9a-f]{64}$`)
)

// ExerciseRecord is the signed, one-file storage format for an operator
// exercise. A record file contains one record and is named by the operator;
// the runbook field is the authoritative association.
type ExerciseRecord struct {
	Runbook        string     `json:"runbook"`
	Environment    string     `json:"environment"`
	StartedAt      time.Time  `json:"startedAt"`
	EndedAt        time.Time  `json:"endedAt"`
	Alert          string     `json:"alert"`
	Operator       string     `json:"operator"`
	Result         string     `json:"result"`
	EvidenceURIs   []string   `json:"evidenceUris"`
	ArtifactSHA256 string     `json:"artifactSha256"`
	Signature      *Signature `json:"signature"`
}

// Signature is an Ed25519 signature over the canonical record with Signature
// removed. Keeping the envelope small makes independent verification easy.
type Signature struct {
	Type  string `json:"type"`
	KID   string `json:"kid"`
	Value string `json:"value"`
}

// Finding identifies one rejected record or missing runbook.
type Finding struct {
	File    string `json:"file,omitempty"`
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ValidationReport is returned even when validation fails, so an external
// conformance driver can preserve the complete set of findings as evidence.
type ValidationReport struct {
	Records  []ExerciseRecord `json:"records,omitempty"`
	Missing  []string         `json:"missing,omitempty"`
	Findings []Finding        `json:"findings,omitempty"`
}

// RequiredRunbooks returns the immutable runbook set required by SPEC 32.
func RequiredRunbooks() []string {
	return []string{
		"agent-runaway-cost.md",
		"artifact-integrity-failure.md",
		"budget-reconciliation.md",
		"control-plane-outage.md",
		"database-failover.md",
		"disaster-recovery.md",
		"event-bus-backlog.md",
		"key-rotation.md",
		"knowledge-corruption.md",
		"model-provider-outage.md",
		"rollback-release.md",
		"sandbox-escape-suspected.md",
		"secret-exposure.md",
		"third-attempt-user-escalation.md",
		"workflow-stuck.md",
	}
}

// SignRecord returns a copy of record signed by privateKey. It is intended
// for an operator's evidence producer; production records must be signed by
// the controlled operator or KMS workflow, not generated by the validator.
func SignRecord(record ExerciseRecord, privateKey ed25519.PrivateKey, kid string) (ExerciseRecord, error) {
	if len(privateKey) != ed25519.PrivateKeySize || !safeField(kid, maxFieldBytes) {
		return ExerciseRecord{}, ErrInvalidEvidence
	}
	payload, err := signaturePayload(record)
	if err != nil {
		return ExerciseRecord{}, err
	}
	signed := record
	signed.Signature = &Signature{
		Type:  "Ed25519",
		KID:   kid,
		Value: base64.RawURLEncoding.EncodeToString(ed25519.Sign(privateKey, payload)),
	}
	return signed, nil
}

// VerifyRecord verifies a record signature without applying freshness or
// required-runbook policy. Call ValidateRunbookEvidence for the full gate.
func VerifyRecord(record ExerciseRecord, publicKey ed25519.PublicKey, kid string) error {
	if len(publicKey) != ed25519.PublicKeySize || record.Signature == nil || record.Signature.Type != "Ed25519" || record.Signature.KID != kid {
		return ErrInvalidEvidence
	}
	value, err := base64.RawURLEncoding.DecodeString(record.Signature.Value)
	if err != nil || len(value) != ed25519.SignatureSize {
		return ErrInvalidEvidence
	}
	payload, err := signaturePayload(record)
	if err != nil || !ed25519.Verify(publicKey, payload, value) {
		return ErrInvalidEvidence
	}
	return nil
}

// ValidateRunbookEvidence validates all JSON records in evidenceDir against
// the required repository runbooks. It intentionally does not create records
// or infer success from a target's self-report.
func ValidateRunbookEvidence(root, evidenceDir string, now time.Time, publicKey ed25519.PublicKey, kid string) (ValidationReport, error) {
	report := ValidationReport{Records: []ExerciseRecord{}, Missing: []string{}, Findings: []Finding{}}
	if strings.TrimSpace(root) == "" || strings.TrimSpace(evidenceDir) == "" || len(publicKey) != ed25519.PublicKeySize || !safeField(kid, maxFieldBytes) {
		report.Findings = append(report.Findings, Finding{Code: "INVALID_ARGUMENT", Message: "root, evidence directory, public key, and key id are required"})
		return report, ErrInvalidEvidence
	}
	if now.IsZero() {
		now = time.Now().UTC()
	}
	now = now.UTC()
	root, err := filepath.Abs(root)
	if err != nil {
		report.Findings = append(report.Findings, Finding{Code: "ROOT_INVALID", Message: err.Error()})
		return report, ErrInvalidEvidence
	}
	if err := validateRunbookFiles(root, &report); err != nil {
		return report, err
	}
	entries, err := os.ReadDir(evidenceDir)
	if err != nil {
		report.Findings = append(report.Findings, Finding{Code: "EVIDENCE_DIRECTORY_READ", Message: err.Error()})
		return report, ErrInvalidEvidence
	}
	if len(entries) > maxEvidenceFiles {
		report.Findings = append(report.Findings, Finding{Code: "EVIDENCE_LIMIT", Message: "too many evidence files"})
		return report, ErrInvalidEvidence
	}
	seen := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".json" {
			continue
		}
		path := filepath.Join(evidenceDir, entry.Name())
		info, statErr := os.Lstat(path)
		if statErr != nil {
			report.Findings = append(report.Findings, Finding{File: entry.Name(), Code: "EVIDENCE_STAT", Message: statErr.Error()})
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			report.Findings = append(report.Findings, Finding{File: entry.Name(), Code: "EVIDENCE_FILE_INVALID", Message: "record must be a regular non-symlink file"})
			continue
		}
		record, decodeErr := decodeRecord(path, info.Size())
		if decodeErr != nil {
			report.Findings = append(report.Findings, Finding{File: entry.Name(), Code: "EVIDENCE_DECODE", Message: decodeErr.Error()})
			continue
		}
		if _, duplicate := seen[record.Runbook]; duplicate {
			report.Findings = append(report.Findings, Finding{File: entry.Name(), Code: "RUNBOOK_DUPLICATE", Message: record.Runbook})
			continue
		}
		seen[record.Runbook] = struct{}{}
		if validationErr := validateRecord(record, now, publicKey, kid); validationErr != nil {
			report.Findings = append(report.Findings, Finding{File: entry.Name(), Code: findingCode(validationErr), Message: validationErr.Error()})
			continue
		}
		report.Records = append(report.Records, record)
	}
	required := RequiredRunbooks()
	for _, runbook := range required {
		if _, ok := seen[runbook]; !ok {
			report.Missing = append(report.Missing, runbook)
		}
	}
	if len(report.Missing) > 0 {
		report.Findings = append(report.Findings, Finding{Code: "RUNBOOK_EVIDENCE_MISSING", Message: strings.Join(report.Missing, ",")})
	}
	sort.Slice(report.Records, func(left, right int) bool { return report.Records[left].Runbook < report.Records[right].Runbook })
	if len(report.Findings) > 0 {
		if len(report.Missing) > 0 {
			return report, ErrEvidenceMissing
		}
		return report, ErrInvalidEvidence
	}
	return report, nil
}

func validateRunbookFiles(root string, report *ValidationReport) error {
	directory := filepath.Join(root, "runbooks")
	for _, runbook := range RequiredRunbooks() {
		path := filepath.Join(directory, runbook)
		info, err := os.Lstat(path)
		if err != nil {
			report.Findings = append(report.Findings, Finding{File: filepath.Join("runbooks", runbook), Code: "RUNBOOK_MISSING", Message: err.Error()})
			continue
		}
		if info.Mode()&os.ModeSymlink != 0 || !info.Mode().IsRegular() {
			report.Findings = append(report.Findings, Finding{File: filepath.Join("runbooks", runbook), Code: "RUNBOOK_INVALID", Message: "runbook must be a regular non-symlink file"})
		}
	}
	if len(report.Findings) > 0 {
		return ErrInvalidEvidence
	}
	return nil
}

func decodeRecord(path string, size int64) (ExerciseRecord, error) {
	if size < 0 || size > maxRecordBytes {
		return ExerciseRecord{}, fmt.Errorf("record exceeds %d bytes", maxRecordBytes)
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return ExerciseRecord{}, err
	}
	if len(content) > maxRecordBytes {
		return ExerciseRecord{}, fmt.Errorf("record exceeds %d bytes", maxRecordBytes)
	}
	decoder := json.NewDecoder(bytes.NewReader(content))
	decoder.DisallowUnknownFields()
	var record ExerciseRecord
	if err := decoder.Decode(&record); err != nil {
		return ExerciseRecord{}, err
	}
	var trailing any
	if err := decoder.Decode(&trailing); err != io.EOF {
		if err == nil {
			return ExerciseRecord{}, errors.New("multiple JSON values")
		}
		return ExerciseRecord{}, err
	}
	return record, nil
}

func validateRecord(record ExerciseRecord, now time.Time, publicKey ed25519.PublicKey, kid string) error {
	required := make(map[string]struct{}, len(RequiredRunbooks()))
	for _, runbook := range RequiredRunbooks() {
		required[runbook] = struct{}{}
	}
	if _, ok := required[record.Runbook]; !ok || filepath.Base(record.Runbook) != record.Runbook || strings.Contains(record.Runbook, "\\") {
		return fmt.Errorf("unknown runbook %q", record.Runbook)
	}
	for name, value := range map[string]string{"environment": record.Environment, "alert": record.Alert, "operator": record.Operator, "result": record.Result} {
		if !safeField(value, maxFieldBytes) {
			return fmt.Errorf("%s is required and bounded", name)
		}
	}
	if record.StartedAt.IsZero() || record.EndedAt.IsZero() || record.EndedAt.Before(record.StartedAt) {
		return errors.New("exercise timestamps are invalid")
	}
	if record.EndedAt.After(now) {
		return ErrEvidenceStale
	}
	if now.Sub(record.EndedAt) > DefaultRunbookMaxAge {
		return ErrEvidenceStale
	}
	if len(record.EvidenceURIs) == 0 || len(record.EvidenceURIs) > 32 {
		return errors.New("at least one evidence URI is required")
	}
	for _, uri := range record.EvidenceURIs {
		if len(uri) == 0 || len(uri) > maxEvidenceURIBytes || strings.TrimSpace(uri) != uri || strings.ContainsAny(uri, "\r\n\x00") {
			return errors.New("evidence URI is invalid")
		}
	}
	if !digestPattern.MatchString(record.ArtifactSHA256) {
		return errors.New("artifactSha256 must be a lowercase sha256 digest")
	}
	return VerifyRecord(record, publicKey, kid)
}

func signaturePayload(record ExerciseRecord) ([]byte, error) {
	record.Signature = nil
	encoded, err := json.Marshal(record)
	if err != nil {
		return nil, err
	}
	return canonicaljson.Canonicalize(encoded)
}

func safeField(value string, maximum int) bool {
	return value != "" && len(value) <= maximum && strings.TrimSpace(value) == value && !strings.ContainsRune(value, 0)
}

func findingCode(err error) string {
	switch {
	case errors.Is(err, ErrEvidenceStale):
		return "RUNBOOK_EVIDENCE_STALE"
	case errors.Is(err, ErrInvalidEvidence):
		return "RUNBOOK_EVIDENCE_INVALID"
	default:
		return "RUNBOOK_RECORD_INVALID"
	}
}
