package sdkgen

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/format"
	"regexp"
	"sort"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

var operationIDPattern = regexp.MustCompile(`^[a-z][A-Za-z0-9]{1,127}$`)

type operation struct {
	OperationID string `yaml:"operationId"`
}

type pathItem struct {
	Ref         string     `yaml:"$ref"`
	ExtensionID string     `yaml:"x-operation-id"`
	Get         *operation `yaml:"get"`
	Post        *operation `yaml:"post"`
	Put         *operation `yaml:"put"`
	Patch       *operation `yaml:"patch"`
	Delete      *operation `yaml:"delete"`
}

type document struct {
	OpenAPI string              `yaml:"openapi"`
	Paths   map[string]pathItem `yaml:"paths"`
}

type Operation struct {
	ID     string
	Method string
	Path   string
}

type Outputs struct {
	Go         []byte
	TypeScript []byte
	Python     []byte
}

func Generate(input []byte) (Outputs, error) {
	var spec document
	decoder := yaml.NewDecoder(bytes.NewReader(input))
	decoder.KnownFields(false)
	if err := decoder.Decode(&spec); err != nil || spec.OpenAPI != "3.2.0" || len(spec.Paths) == 0 {
		return Outputs{}, errors.New("invalid OpenAPI document")
	}
	operations, err := collectOperations(spec.Paths)
	if err != nil {
		return Outputs{}, err
	}
	digest := sha256.Sum256(input)
	sourceDigest := "sha256:" + hex.EncodeToString(digest[:])
	goSource, err := generateGo(operations, sourceDigest)
	if err != nil {
		return Outputs{}, err
	}
	return Outputs{Go: goSource, TypeScript: generateTypeScript(operations, sourceDigest), Python: generatePython(operations, sourceDigest)}, nil
}

func collectOperations(paths map[string]pathItem) ([]Operation, error) {
	operations := make([]Operation, 0, len(paths))
	seen := make(map[string]struct{})
	for route, item := range paths {
		if route == "" || !strings.HasPrefix(route, "/") {
			return nil, errors.New("invalid OpenAPI path")
		}
		methods := []struct {
			name      string
			operation *operation
		}{{"GET", item.Get}, {"POST", item.Post}, {"PUT", item.Put}, {"PATCH", item.Patch}, {"DELETE", item.Delete}}
		found := false
		for _, method := range methods {
			if method.operation == nil {
				continue
			}
			found = true
			if err := appendOperation(&operations, seen, Operation{ID: method.operation.OperationID, Method: method.name, Path: route}); err != nil {
				return nil, err
			}
		}
		if item.Ref != "" {
			if found || !strings.HasPrefix(item.Ref, "#/components/pathItems/") {
				return nil, errors.New("unsupported referenced PathItem")
			}
			if err := appendOperation(&operations, seen, Operation{ID: item.ExtensionID, Method: "POST", Path: route}); err != nil {
				return nil, err
			}
		}
	}
	sort.Slice(operations, func(left, right int) bool { return operations[left].ID < operations[right].ID })
	return operations, nil
}

func appendOperation(operations *[]Operation, seen map[string]struct{}, candidate Operation) error {
	if !operationIDPattern.MatchString(candidate.ID) || candidate.Method == "" || candidate.Path == "" {
		return errors.New("operation has no stable identifier")
	}
	if _, duplicate := seen[candidate.ID]; duplicate {
		return errors.New("duplicate operation identifier")
	}
	seen[candidate.ID] = struct{}{}
	*operations = append(*operations, candidate)
	return nil
}

func generateGo(operations []Operation, digest string) ([]byte, error) {
	var output bytes.Buffer
	output.WriteString(`// Code generated by aor-sdkgen; DO NOT EDIT.
package aor

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const OpenAPISHA256 = "` + digest + `"

type TokenProvider func(context.Context) (string, error)

type Client struct {
	baseURL string
	httpClient *http.Client
	tokenProvider TokenProvider
}

type RequestOptions struct {
	PathParameters map[string]string
	Query url.Values
	Headers http.Header
	Body any
}

func NewClient(baseURL string, httpClient *http.Client, tokenProvider TokenProvider) (*Client, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return nil, errors.New("AOR SDK requires an HTTPS base URL")
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, tokenProvider: tokenProvider}, nil
}

func (c *Client) request(ctx context.Context, method, route string, options RequestOptions) (*http.Response, error) {
	if c == nil || ctx == nil {
		return nil, errors.New("invalid AOR SDK request")
	}
	expanded, err := expandPath(route, options.PathParameters)
	if err != nil {
		return nil, err
	}
	endpoint, err := url.Parse(c.baseURL + expanded)
	if err != nil {
		return nil, err
	}
	endpoint.RawQuery = options.Query.Encode()
	var body bytes.Buffer
	var bodyReader io.Reader
	if options.Body != nil {
		if err := json.NewEncoder(&body).Encode(options.Body); err != nil {
			return nil, err
		}
		bodyReader = &body
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint.String(), bodyReader)
	if err != nil {
		return nil, err
	}
	request.Header = options.Headers.Clone()
	if request.Header == nil {
		request.Header = make(http.Header)
	}
	request.Header.Set("Accept", "application/json")
	if options.Body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	if c.tokenProvider != nil {
		token, tokenErr := c.tokenProvider(ctx)
		if tokenErr != nil || token == "" || strings.ContainsAny(token, "\r\n") {
			return nil, errors.New("AOR SDK token provider failed")
		}
		request.Header.Set("Authorization", "Bearer "+token)
	}
	return c.httpClient.Do(request)
}

func expandPath(route string, parameters map[string]string) (string, error) {
	for {
		start := strings.IndexByte(route, '{')
		if start < 0 {
			return route, nil
		}
		end := strings.IndexByte(route[start:], '}')
		if end < 2 {
			return "", errors.New("invalid OpenAPI path template")
		}
		end += start
		name := route[start+1:end]
		value, found := parameters[name]
		if !found || value == "" {
			return "", errors.New("missing OpenAPI path parameter")
		}
		route = route[:start] + url.PathEscape(value) + route[end+1:]
	}
}

`)
	for _, item := range operations {
		fmt.Fprintf(&output, "func (c *Client) %s(ctx context.Context, options RequestOptions) (*http.Response, error) {\n\treturn c.request(ctx, %q, %q, options)\n}\n\n", exported(item.ID), item.Method, item.Path)
	}
	return format.Source(output.Bytes())
}

func generateTypeScript(operations []Operation, digest string) []byte {
	var output bytes.Buffer
	output.WriteString(`// Code generated by aor-sdkgen; DO NOT EDIT.
export const OPENAPI_SHA256 = "` + digest + `";

export type RequestOptions = {
  pathParameters?: Record<string, string>;
  query?: Record<string, string | readonly string[]>;
  headers?: Record<string, string>;
  body?: unknown;
};

export type Transport = (input: string, init: RequestInit) => Promise<Response>;
export type TokenProvider = () => string | Promise<string>;

export class AORClient {
  private readonly baseURL: string;
  private readonly transport: Transport;
  private readonly tokenProvider?: TokenProvider;

  constructor(baseURL: string, transport: Transport = fetch, tokenProvider?: TokenProvider) {
    const parsed = new URL(baseURL);
    if (parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.search || parsed.hash) {
      throw new Error("AOR SDK requires an HTTPS base URL");
    }
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.transport = transport;
    this.tokenProvider = tokenProvider;
  }

  private async request(method: string, route: string, options: RequestOptions): Promise<Response> {
    const parameters = options.pathParameters ?? {};
    const expanded = route.replace(/\{([^}]+)\}/g, (_match, name: string) => {
      const value = parameters[name];
      if (!value) throw new Error("missing OpenAPI path parameter");
      return encodeURIComponent(value);
    });
    const endpoint = new URL(this.baseURL + expanded);
    for (const [name, value] of Object.entries(options.query ?? {})) {
      for (const item of Array.isArray(value) ? value : [value]) endpoint.searchParams.append(name, item);
    }
    const headers = new Headers(options.headers ?? {});
    headers.set("Accept", "application/json");
    if (options.body !== undefined) headers.set("Content-Type", "application/json");
    if (this.tokenProvider) {
      const token = await this.tokenProvider();
      if (!token || /[\r\n]/.test(token)) throw new Error("AOR SDK token provider failed");
      headers.set("Authorization", "Bearer " + token);
    }
    return this.transport(endpoint.toString(), {method, headers, body: options.body === undefined ? undefined : JSON.stringify(options.body)});
  }

`)
	for _, item := range operations {
		fmt.Fprintf(&output, "  %s(options: RequestOptions = {}): Promise<Response> {\n    return this.request(%q, %q, options);\n  }\n\n", item.ID, item.Method, item.Path)
	}
	output.WriteString("}\n")
	return output.Bytes()
}

func generatePython(operations []Operation, digest string) []byte {
	var output bytes.Buffer
	output.WriteString(`# Code generated by aor-sdkgen; DO NOT EDIT.
import json
from urllib.parse import quote, urlencode, urlparse
from urllib.request import Request, urlopen

OPENAPI_SHA256 = "` + digest + `"


class AORClient:
    def __init__(self, base_url, transport=urlopen, token_provider=None):
        parsed = urlparse(base_url)
        if parsed.scheme != "https" or not parsed.netloc or parsed.username or parsed.password or parsed.query or parsed.fragment:
            raise ValueError("AOR SDK requires an HTTPS base URL")
        self._base_url = base_url.rstrip("/")
        self._transport = transport
        self._token_provider = token_provider

    def _request(self, method, route, options):
        options = options or {}
        parameters = options.get("path_parameters", {})
        while "{" in route:
            start = route.index("{")
            end = route.find("}", start)
            if end < 0:
                raise ValueError("invalid OpenAPI path template")
            name = route[start + 1:end]
            value = parameters.get(name)
            if not value:
                raise ValueError("missing OpenAPI path parameter")
            route = route[:start] + quote(str(value), safe="") + route[end + 1:]
        query = urlencode(options.get("query", {}), doseq=True)
        endpoint = self._base_url + route + (("?" + query) if query else "")
        headers = dict(options.get("headers", {}))
        headers["Accept"] = "application/json"
        body = options.get("body")
        data = None
        if body is not None:
            data = json.dumps(body, separators=(",", ":")).encode("utf-8")
            headers["Content-Type"] = "application/json"
        if self._token_provider is not None:
            token = self._token_provider()
            if not token or "\r" in token or "\n" in token:
                raise ValueError("AOR SDK token provider failed")
            headers["Authorization"] = "Bearer " + token
        return self._transport(Request(endpoint, data=data, headers=headers, method=method))

`)
	for _, item := range operations {
		fmt.Fprintf(&output, "    def %s(self, options=None):\n        return self._request(%q, %q, options)\n\n", snake(item.ID), item.Method, item.Path)
	}
	return output.Bytes()
}

func exported(value string) string {
	runes := []rune(value)
	runes[0] = unicode.ToUpper(runes[0])
	return string(runes)
}

func snake(value string) string {
	var output strings.Builder
	for index, character := range value {
		if unicode.IsUpper(character) {
			if index > 0 {
				output.WriteByte('_')
			}
			output.WriteRune(unicode.ToLower(character))
			continue
		}
		output.WriteRune(character)
	}
	return output.String()
}
