# Code generated by aor-sdkgen; DO NOT EDIT.
import json
from urllib.parse import quote, urlencode, urlparse
from urllib.request import Request, urlopen

OPENAPI_SHA256 = "sha256:93376a9dac67faf738c31761b7f37fcbc2dd82ffe9e492af773c5c067af79431"


class AORClient:
    def __init__(self, base_url, transport=urlopen, token_provider=None):
        parsed = urlparse(base_url)
        if parsed.scheme != "https" or not parsed.netloc or parsed.username or parsed.password or parsed.query or parsed.fragment:
            raise ValueError("AOR SDK requires an HTTPS base URL")
        self._base_url = base_url.rstrip("/")
        self._transport = transport
        self._token_provider = token_provider

    def _request(self, method, route, options):
        options = options or {}
        parameters = options.get("path_parameters", {})
        while "{" in route:
            start = route.index("{")
            end = route.find("}", start)
            if end < 0:
                raise ValueError("invalid OpenAPI path template")
            name = route[start + 1:end]
            value = parameters.get(name)
            if not value:
                raise ValueError("missing OpenAPI path parameter")
            route = route[:start] + quote(str(value), safe="") + route[end + 1:]
        query = urlencode(options.get("query", {}), doseq=True)
        endpoint = self._base_url + route + (("?" + query) if query else "")
        headers = dict(options.get("headers", {}))
        headers["Accept"] = "application/json"
        body = options.get("body")
        data = None
        if body is not None:
            data = json.dumps(body, separators=(",", ":")).encode("utf-8")
            headers["Content-Type"] = "application/json"
        if self._token_provider is not None:
            token = self._token_provider()
            if not token or "\r" in token or "\n" in token:
                raise ValueError("AOR SDK token provider failed")
            headers["Authorization"] = "Bearer " + token
        return self._transport(Request(endpoint, data=data, headers=headers, method=method))

    def abort_project(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:abort", options)

    def adjust_budget(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/budgets:adjust", options)

    def approve_goal_spec(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/goal/specs/{version}:approve", options)

    def approve_project_release(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:approve-release", options)

    def archive_project(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:archive", options)

    def change_goal(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/goal:change", options)

    def create_project(self, options=None):
        return self._request("POST", "/v1/projects", options)

    def decide_task(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/tasks/{taskId}/decisions", options)

    def export_project(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/export", options)

    def get_artifact(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/artifacts/{artifactId}", options)

    def get_budget_usage(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/budgets/usage", options)

    def get_budgets(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/budgets", options)

    def get_goal_spec(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/goal/specs/{version}", options)

    def get_knowledge_manifest(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/knowledge/manifest", options)

    def get_plan(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/plans/{version}", options)

    def get_project(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}", options)

    def get_project_state(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/state", options)

    def get_task(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/tasks/{taskId}", options)

    def get_task_decision_report(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/tasks/{taskId}/decision-report", options)

    def get_usage(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/usage", options)

    def list_artifacts(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/artifacts", options)

    def list_goal_specs(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/goal/specs", options)

    def list_plans(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/plans", options)

    def list_task_audits(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/tasks/{taskId}/audits", options)

    def list_task_submissions(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/tasks/{taskId}/submissions", options)

    def list_tasks(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/tasks", options)

    def pause_project(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:pause", options)

    def probe_sandboxes(self, options=None):
        return self._request("POST", "/v1/admin/sandboxes:probe", options)

    def read_knowledge_range(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/knowledge:read-range", options)

    def reject_goal_spec(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/goal/specs/{version}:reject", options)

    def request_project_deletion(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:request-deletion", options)

    def resume_project(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}:resume", options)

    def run_doctor(self, options=None):
        return self._request("POST", "/v1/admin/doctor", options)

    def search_knowledge(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/knowledge:search", options)

    def send_goal_message(self, options=None):
        return self._request("POST", "/v1/projects/{projectId}/goal/messages", options)

    def stream_project_events(self, options=None):
        return self._request("GET", "/v1/projects/{projectId}/events", options)

    def test_policies(self, options=None):
        return self._request("POST", "/v1/admin/policies:test", options)

