// Code generated by aor-sdkgen; DO NOT EDIT.
export const OPENAPI_SHA256 = "sha256:38d74eafafcc06062803cc39c1c41c69e9fee39015835bc1132266dea9c9ed14";

export type RequestOptions = {
  pathParameters?: Record<string, string>;
  query?: Record<string, string | readonly string[]>;
  headers?: Record<string, string>;
  body?: unknown;
};

export type Transport = (input: string, init: RequestInit) => Promise<Response>;
export type TokenProvider = () => string | Promise<string>;

export class AORClient {
  private readonly baseURL: string;
  private readonly transport: Transport;
  private readonly tokenProvider?: TokenProvider;

  constructor(baseURL: string, transport: Transport = fetch, tokenProvider?: TokenProvider) {
    const parsed = new URL(baseURL);
    if (parsed.protocol !== "https:" || parsed.username || parsed.password || parsed.search || parsed.hash) {
      throw new Error("AOR SDK requires an HTTPS base URL");
    }
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.transport = transport;
    this.tokenProvider = tokenProvider;
  }

  private async request(method: string, route: string, options: RequestOptions): Promise<Response> {
    const parameters = options.pathParameters ?? {};
    const expanded = route.replace(/\{([^}]+)\}/g, (_match, name: string) => {
      const value = parameters[name];
      if (!value) throw new Error("missing OpenAPI path parameter");
      return encodeURIComponent(value);
    });
    const endpoint = new URL(this.baseURL + expanded);
    for (const [name, value] of Object.entries(options.query ?? {})) {
      for (const item of Array.isArray(value) ? value : [value]) endpoint.searchParams.append(name, item);
    }
    const headers = new Headers(options.headers ?? {});
    headers.set("Accept", "application/json");
    if (options.body !== undefined) headers.set("Content-Type", "application/json");
    if (this.tokenProvider) {
      const token = await this.tokenProvider();
      if (!token || /[\r\n]/.test(token)) throw new Error("AOR SDK token provider failed");
      headers.set("Authorization", "Bearer " + token);
    }
    return this.transport(endpoint.toString(), {method, headers, body: options.body === undefined ? undefined : JSON.stringify(options.body)});
  }

  abortProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:abort", options);
  }

  adjustBudget(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/budgets:adjust", options);
  }

  approveGoalSpec(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/goal/specs/{version}:approve", options);
  }

  approveProjectRelease(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:approve-release", options);
  }

  archiveProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:archive", options);
  }

  changeGoal(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/goal:change", options);
  }

  createProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects", options);
  }

  decideTask(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/tasks/{taskId}/decisions", options);
  }

  exportProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/export", options);
  }

  getArtifact(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/artifacts/{artifactId}", options);
  }

  getBudgetUsage(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/budgets/usage", options);
  }

  getBudgets(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/budgets", options);
  }

  getGoalSpec(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/goal/specs/{version}", options);
  }

  getKnowledgeManifest(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/knowledge/manifest", options);
  }

  getPlan(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/plans/{version}", options);
  }

  getProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}", options);
  }

  getProjectState(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/state", options);
  }

  getTask(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/tasks/{taskId}", options);
  }

  getTaskDecisionReport(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/tasks/{taskId}/decision-report", options);
  }

  getUsage(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/usage", options);
  }

  listArtifacts(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/artifacts", options);
  }

  listGoalMessages(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/goal/messages", options);
  }

  listGoalSpecs(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/goal/specs", options);
  }

  listPlans(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/plans", options);
  }

  listTaskAudits(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/tasks/{taskId}/audits", options);
  }

  listTaskSubmissions(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/tasks/{taskId}/submissions", options);
  }

  listTasks(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/tasks", options);
  }

  pauseProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:pause", options);
  }

  probeSandboxes(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/admin/sandboxes:probe", options);
  }

  readKnowledgeRange(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/knowledge:read-range", options);
  }

  rejectGoalSpec(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/goal/specs/{version}:reject", options);
  }

  requestProjectDeletion(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:request-deletion", options);
  }

  resumeProject(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}:resume", options);
  }

  runDoctor(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/admin/doctor", options);
  }

  searchKnowledge(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/knowledge:search", options);
  }

  sendGoalMessage(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/projects/{projectId}/goal/messages", options);
  }

  streamProjectEvents(options: RequestOptions = {}): Promise<Response> {
    return this.request("GET", "/v1/projects/{projectId}/events", options);
  }

  testPolicies(options: RequestOptions = {}): Promise<Response> {
    return this.request("POST", "/v1/admin/policies:test", options);
  }

}
