// Code generated by aor-sdkgen; DO NOT EDIT.
package aor

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"io"
	"net/http"
	"net/url"
	"strings"
)

const OpenAPISHA256 = "sha256:93376a9dac67faf738c31761b7f37fcbc2dd82ffe9e492af773c5c067af79431"

type TokenProvider func(context.Context) (string, error)

type Client struct {
	baseURL       string
	httpClient    *http.Client
	tokenProvider TokenProvider
}

type RequestOptions struct {
	PathParameters map[string]string
	Query          url.Values
	Headers        http.Header
	Body           any
}

func NewClient(baseURL string, httpClient *http.Client, tokenProvider TokenProvider) (*Client, error) {
	parsed, err := url.Parse(baseURL)
	if err != nil || parsed.Scheme != "https" || parsed.Host == "" || parsed.User != nil || parsed.RawQuery != "" || parsed.Fragment != "" {
		return nil, errors.New("AOR SDK requires an HTTPS base URL")
	}
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	return &Client{baseURL: strings.TrimRight(baseURL, "/"), httpClient: httpClient, tokenProvider: tokenProvider}, nil
}

func (c *Client) request(ctx context.Context, method, route string, options RequestOptions) (*http.Response, error) {
	if c == nil || ctx == nil {
		return nil, errors.New("invalid AOR SDK request")
	}
	expanded, err := expandPath(route, options.PathParameters)
	if err != nil {
		return nil, err
	}
	endpoint, err := url.Parse(c.baseURL + expanded)
	if err != nil {
		return nil, err
	}
	endpoint.RawQuery = options.Query.Encode()
	var body bytes.Buffer
	var bodyReader io.Reader
	if options.Body != nil {
		if err := json.NewEncoder(&body).Encode(options.Body); err != nil {
			return nil, err
		}
		bodyReader = &body
	}
	request, err := http.NewRequestWithContext(ctx, method, endpoint.String(), bodyReader)
	if err != nil {
		return nil, err
	}
	request.Header = options.Headers.Clone()
	if request.Header == nil {
		request.Header = make(http.Header)
	}
	request.Header.Set("Accept", "application/json")
	if options.Body != nil {
		request.Header.Set("Content-Type", "application/json")
	}
	if c.tokenProvider != nil {
		token, tokenErr := c.tokenProvider(ctx)
		if tokenErr != nil || token == "" || strings.ContainsAny(token, "\r\n") {
			return nil, errors.New("AOR SDK token provider failed")
		}
		request.Header.Set("Authorization", "Bearer "+token)
	}
	return c.httpClient.Do(request)
}

func expandPath(route string, parameters map[string]string) (string, error) {
	for {
		start := strings.IndexByte(route, '{')
		if start < 0 {
			return route, nil
		}
		end := strings.IndexByte(route[start:], '}')
		if end < 2 {
			return "", errors.New("invalid OpenAPI path template")
		}
		end += start
		name := route[start+1 : end]
		value, found := parameters[name]
		if !found || value == "" {
			return "", errors.New("missing OpenAPI path parameter")
		}
		route = route[:start] + url.PathEscape(value) + route[end+1:]
	}
}

func (c *Client) AbortProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:abort", options)
}

func (c *Client) AdjustBudget(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/budgets:adjust", options)
}

func (c *Client) ApproveGoalSpec(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/goal/specs/{version}:approve", options)
}

func (c *Client) ApproveProjectRelease(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:approve-release", options)
}

func (c *Client) ArchiveProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:archive", options)
}

func (c *Client) ChangeGoal(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/goal:change", options)
}

func (c *Client) CreateProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects", options)
}

func (c *Client) DecideTask(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/tasks/{taskId}/decisions", options)
}

func (c *Client) ExportProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/export", options)
}

func (c *Client) GetArtifact(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/artifacts/{artifactId}", options)
}

func (c *Client) GetBudgetUsage(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/budgets/usage", options)
}

func (c *Client) GetBudgets(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/budgets", options)
}

func (c *Client) GetGoalSpec(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/goal/specs/{version}", options)
}

func (c *Client) GetKnowledgeManifest(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/knowledge/manifest", options)
}

func (c *Client) GetPlan(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/plans/{version}", options)
}

func (c *Client) GetProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}", options)
}

func (c *Client) GetProjectState(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/state", options)
}

func (c *Client) GetTask(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/tasks/{taskId}", options)
}

func (c *Client) GetTaskDecisionReport(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/tasks/{taskId}/decision-report", options)
}

func (c *Client) GetUsage(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/usage", options)
}

func (c *Client) ListArtifacts(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/artifacts", options)
}

func (c *Client) ListGoalSpecs(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/goal/specs", options)
}

func (c *Client) ListPlans(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/plans", options)
}

func (c *Client) ListTaskAudits(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/tasks/{taskId}/audits", options)
}

func (c *Client) ListTaskSubmissions(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/tasks/{taskId}/submissions", options)
}

func (c *Client) ListTasks(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/tasks", options)
}

func (c *Client) PauseProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:pause", options)
}

func (c *Client) ProbeSandboxes(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/admin/sandboxes:probe", options)
}

func (c *Client) ReadKnowledgeRange(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/knowledge:read-range", options)
}

func (c *Client) RejectGoalSpec(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/goal/specs/{version}:reject", options)
}

func (c *Client) RequestProjectDeletion(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:request-deletion", options)
}

func (c *Client) ResumeProject(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}:resume", options)
}

func (c *Client) RunDoctor(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/admin/doctor", options)
}

func (c *Client) SearchKnowledge(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/knowledge:search", options)
}

func (c *Client) SendGoalMessage(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/projects/{projectId}/goal/messages", options)
}

func (c *Client) StreamProjectEvents(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "GET", "/v1/projects/{projectId}/events", options)
}

func (c *Client) TestPolicies(ctx context.Context, options RequestOptions) (*http.Response, error) {
	return c.request(ctx, "POST", "/v1/admin/policies:test", options)
}
